[build]
  publish = "public"
  command = "make"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/saschazar21/sascha.work"
  GO111MODULE = "on"
  GOARCH = "amd64"
  GOOS = "linux"
  NODE_VERSION = "22.x"

[[redirects]]
  from = "/api/v1/project/:owner/:repo"
  to = "/.netlify/functions/v1_project"
  status = 200
  force = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"
    
[[headers]]
  for = "/feed.json"
  [headers.values]
    Content-Type = "application/feed+json"
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml"
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/vnd.api+json"
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"