name: Test

on:
  workflow_call:

jobs:
  test:
    name: Set up build environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache-dependency-path: |
            go.sum

      - name: Tidy up
        run: go mod tidy

      - name: Test
        run: make test
